### ISSUE TITLE
Support for custom options in quick_menu

### ISSUE THREAD

**Issue by haru02w** [j-morano/buffer_manager.nvim#20]
I really would like to use relative numbers to reorder my buffers inside quick_menu.
(of course, setting line_keys="")

**Comment by j-morano** [comment]
Hi! Thank you for the feedback. I added a commit solving this issue. Now you can specify in the setup function your own options for the buffer menu window. Here is an example:
```lua
require("buffer_manager").setup({
  win_extra_options = {
    relativenumber = true,
  },
})
```
I hope this solution works for you. If not, feel free to reopen the issue.
