### ISSUE TITLE
[bug] bmui.nav_file(i) not working until bmui.toggle_quick_menu()

### ISSUE THREAD

**Issue by haru02w** [j-morano/buffer_manager.nvim#22]
If I have file1 open and then open file2 (for example, using Telescope), I cannot go back to file2 if I move out until opening and closing quick_menu.

Seems to be really simple thing to fix, but I'm not good with lua yet.

**Comment by j-morano** [comment]
Hello! Thanks for the feedback. You are right, this was not working properly.
I have added a commit that I believe fixes the problem. Please check if it is working OK for you, and reopen the issue if it does not.
