### ISSUE TITLE
if no buffer is opened, throws an error

### ISSUE THREAD

**Issue by pwnwriter** [j-morano/buffer_manager.nvim#23]
Hello,

When there is no buffer opened and the key to switch to the last buffer is pressed, it throws the following error, Probably not that big issue, but it'd be good it it hides those errors instead. :)

![foo](https://github.com/j-morano/buffer_manager.nvim/assets/90331517/b9dd98be-0270-43c3-af6f-052fde7dc673)

**Comment by j-morano** [comment]
Hi, Thanks for the feedback. I haven't had time to take a look at this bug yet, but I see you have closed the issue. It doesn't happen anymore?
