### ISSUE TITLE
Show buffer indicators

### ISSUE THREAD

**Issue by thedenisnikulin** [j-morano/buffer_manager.nvim#28]
When running `:ls`, you can see buffer indicators (flags), but this plugin doesn't have them so it's quite hard to navigate between buffers. I sometimes clean unused buffers, but I need to know whether they were modified or not so I can safely close them. I really like the idea of this plugin, but lack of buffer indicators make it quite inconvenient to use.

**Comment by j-morano** [comment]
Hello. Thanks for the feedback. I have a question. Are you interested in seeing all the indicators or just the modified buffer? Because if you are only or mainly interested in that one, the plugin provides a way of highlighting modified buffers. You just have to configure the highlight group `BufferManagerModified` in your config. For example:
```vim
hi BufferManagerModified ctermfg=19 guifg=#0000af
```
Anyway, thank you for opening the issue, because I just realized that this information is not available in the README.

**Comment by thedenisnikulin** [comment]
Hello, thanks for the reply! Honestly for now seeing only information about modified buffer will do. Didn't know that I can highlight it, thanks for the tip. It would be really great though to have all the buffer indicators available in the future releases, I believe it will make it fully compatible with how vim works (and you never gonna be running `:ls`).

**Comment by j-morano** [comment]
Hello. I created the branch [buffer-indicators](https://github.com/j-morano/buffer_manager.nvim/tree/buffer-indicators) with the feature. Please let me know if it is working correctly for you.

**Comment by thedenisnikulin** [comment]
Hello, yes, looks right!

![image](https://github.com/j-morano/buffer_manager.nvim/assets/46903210/a6916d91-8aff-4e0c-8519-87c5f5fafb55)

As an idea, how do you think about putting indicators to the front of buffer name? It should be easy because there's a fixed number of maximum indicators per buffer. It would give a nice aligned view. Like `:buffers` command:

![image](https://github.com/j-morano/buffer_manager.nvim/assets/46903210/c5f959da-42f4-44df-80fd-caff09afe04a)

**Comment by j-morano** [comment]
Added another commit. Now you can choose between 'before' and 'after' filenames. Please check again if it is working for you.

**Comment by thedenisnikulin** [comment]
yeah, looking great now!

**Comment by thedenisnikulin** [comment]
should I close it now or wait for you to merge into master?

**Comment by j-morano** [comment]
Thank you for your help with beta testing. I will merge.
