### ISSUE TITLE
What are some/all possible values for `win_extra_options`?

### ISSUE THREAD

**Issue by james-d-mitchell** [j-morano/buffer_manager.nvim#30]
Thanks for the plugin, I'm finding it useful!

The title says it all, what are the possible values for `win_extra_options`? Similarly, what are the possible options for `highlight`? In this repo, the only examples are when these options are empty.

**Comment by phenax** [comment]
- `win_extra_options`: `:help option-list`. (Not a 100% sure what works)
- `highlight`: `:help winhighlight`. The format is `from1:to1,from2:to2`. So like: `Normal:MyCustomNormal`

But yeah, some examples in the README for this would be really helpful.

I am using the following in my config to customize the UI -
```lua
{
    highlight = 'Normal:BufferManagerBorder',
    win_extra_options = {
      winhighlight = 'Normal:BufferManagerNormal',
    },
}
```

**Comment by j-morano** [comment]
Thanks @phenax for the reply. I will add your example to the README.
