### ISSUE TITLE
Feature Request: Give the user a custom function to format the file name

### ISSUE THREAD

**Issue by mycf** [j-morano/buffer_manager.nvim#31]

**Comment by j-morano** [comment]
Hello. Thanks for the feedback. I just added the option `format_function`. Please let me know if it works for you.

**Comment by mycf** [comment]
> Hello. Thanks for the feedback. I just added the option `format_function`. Please let me know if it works for you.你好。感谢您的反馈。我刚刚添加了选项`format_function`。请告诉我它是否适合您。

Thank you for your effort!

work well  with custom hl
<img width="466" alt="image" src="https://github.com/j-morano/buffer_manager.nvim/assets/36999825/1b8cd302-a6bc-438f-aeb1-964bc75f7caf">

**Comment by niamleeson** [comment]
@mycf could you share the format_function you used here?

**Comment by mycf** [comment]
> @mycf could you share the format_function you used here?

@niamleeson The hope can help you
```lua
      format_function = function(file)
        if not file then
          return
        end
        -- for java jar class
        if vim.startswith(file, "jdt:/") then
          local package, name = file:match("/([^/]+)/([^/]+.class)?=")
          return string.format("%s %s", name, package)
        end

        local filename = file:match(".+/([^/]-)$")

        local directory = file:match("(.+)/[^/]-$")
        return string.format("%s %s", filename, directory)
      end,

```

for hl you can read buffer like the following in config function, not like me( violently added here) https://github.com/j-morano/buffer_manager.nvim/blob/7714964bd0e01656cd4090874a0f270e27fb5491/lua/buffer_manager/ui.lua#L326

```lua 
  for index, content in pairs(contents) do
    vim.api.nvim_buf_add_highlight(
      Buffer_manager_bufh,
      -1,
      "TelescopeMatching",
      index - 1,
      0,
      #vim.split(content, " ")[1]
    )
    vim.api.nvim_buf_add_highlight(
      Buffer_manager_bufh,
      -1,
      "TelescopeResultsComment",
      index - 1,
      #vim.split(content, " ")[1],
      -1
    )
  end

```

**Comment by niamleeson** [comment]
Thank you!
